# 服务
services:

  official-website:
    image: ${REGISTRY_REPO}nginx:1.23.3-alpine
    restart: on-failure
    hostname: official-website
    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway
#    volumes:
#      - ./dist:/usr/share/nginx/html
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
