# docker-compose --env-file .env.docker up -d

# 服务
services:

  # pocketbase:
  #   container_name: pocketbase
  #   image: ${MIRROR_REGISTRY_REPO}pocketbase:v0.22.14
  #   # build:
  #   #   context: ./.docker/pocketbase/
  #   #   args:
  #   #     - PB_VERSION:0.22.14
  #   #     - PB_ARCH:amd64
  #   restart: on-failure
  #   hostname: pocketbase
  #   ports:
  #     - 8090:8090
  #   volumes:
  #     - ./pb/pb_data:/pb/pb_data

  official-website:
    container_name: official-website
    image: ${MIRROR_REGISTRY_REPO}nginx:1.23.3-alpine
    restart: on-failure
    hostname: official-website
    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
